### ISSUE TITLE
Implicit feedback

### ISSUE THREAD

**Issue by biswagsingh** [jongwook/spark-ranking-metrics#4]
Will this work for implicit feedback? Number of Buys or hits? Thanks

**Comment by jongwook** [comment]
This library is not specific to implicit or explicit feedback. I happened to reuse the class `org.apache.spark.mllib.recommendation.Rating` for storing the user-item-score triplets, but the goal of this library is just to (reliably) calculate the metrics to evaluate ranking algorithms which ranks user-items using real-numbered scores.

If the implicit feedback is the best information that's available, you could set them as the ground-truth and evaluate your predicted rankings.
